name: Test
on: pull_request
jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Setup Node.js 10.x
        uses: actions/setup-node@main
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: yarn
      - name: Run Spellcheck
        run: yarn spellcheck
