name: Test
on:
  pull_request:
    paths-ignore:
      - "docs/**"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Setup Node.js 10.x
        uses: actions/setup-node@main
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: yarn
      - name: Run Initial Build
        run: yarn build
      - name: Run Test Script
        run: yarn test
